# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chinald' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for Chinald
    pod 'Mantle',           '2.0.7'
    pod 'ReactiveCocoa',    '2.5'
    pod 'GVUserDefaults',   '1.0.2'
    pod 'SDWebImage',       '3.8.1'
    pod 'MBProgressHUD',    '1.0.0'
    pod 'AFNetworking',     '3.1.0'
    pod 'CocoaSecurity',    '1.2.4'
    pod 'Masonry',          '1.0.1'
    pod 'FMDB',             '2.6.2'
    pod 'YTKKeyValueStore', '0.1.2'
    pod 'MJRefresh',        '3.1.9'
    pod 'DateTools',        '1.7.0'
    #  pod 'UTDID', '~> 1.0.0'
    pod 'ZipArchive', '~> 1.4.0'
    pod 'JSONModel', '~> 1.7.0'
    pod 'YYText'
    pod 'SHSPhoneComponent','~> 2.15'
    pod 'DACircularProgress', '~> 2.3'
    pod 'UMCCommon'
    pod 'UMCSecurityPlugins'
    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMCShare/UI'
    # 集成微信(精简版0.2M)
    pod 'UMCShare/Social/ReducedWeChat'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    # 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'
    target 'ChinaldTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'ChinaldUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
